#!/bin/bash
# Github setup script
# pull down repository from remote
git clone https://github.com/erikisaki/Scripting-Lab2.git

# change to specific directory
cd /home/yuxuan/Scripting-Lab2

# set username
git config user.name "erikisaki"

# set erikisaki's email
git config user.email "email@example.com"
